### ISSUE TITLE
Not Building Successfully

### ISSUE THREAD

**Issue by M3ND3X** [skycoin/skycoin-mobilewallet#79]
After I installed all the requirements and took all the steps here when I run the command below 

ionic cordova build android

It will run for sometimes and results the error below

BUILD FAILED in 12s
/root/work/src/github.com/skycoin/skywallet/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find :mobile:.
  Required by:
      project :app

Any fix please?

**Comment by gz-c** [comment]
This code is deprecated and probably does not work out of the box
