### ISSUE TITLE
"Unsafe device" warning stuck

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin-mobilewallet#9]
Reported by _gleam in telegram:

![photo_2017-10-04_07-33-36](https://user-images.githubusercontent.com/26845312/31160552-ad660078-a896-11e7-8a89-b031540794ae.jpg)

"I'm getting this error regardless of my settings..."
"I'm on a Oneplus 2; custom firmware (AOSP/CAF based)"

**Comment by ADepic** [comment]
EXACT SAME HARDWARE/ SOFTWARE & EXACT SAME PROBLEM!

I am running lineage is on my oneplus2, I get this exact error.

**Comment by ADepic** [comment]
Anything?

**Comment by gz-c** [comment]
This is for the beta wallet, which we removed from the app store. It won't work even if it doesn't show the unsafe device warning.
